repos:
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.10.0
    hooks:
    - id: black
      exclude: ocr_lib
      args: ['--line-length', '127']
  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]
        exclude: ocr_lib
  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: ['--ignore=E501,E203,W503', '--max-line-length=127']
        exclude: ocr_lib